# Generated by Django 6.0.1 on 2026-02-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(default='Покрова АМП', max_length=100)),
                ('home_logo', models.ImageField(blank=True, null=True, upload_to='matches/')),
                ('away_team', models.CharField(max_length=100)),
                ('away_logo', models.ImageField(blank=True, null=True, upload_to='matches/')),
                ('date', models.DateTimeField(verbose_name='Дата та час матчу')),
                ('stadium', models.CharField(max_length=200, verbose_name='Стадіон')),
                ('league', models.CharField(default='Чемпіонат України АМП', max_length=100, verbose_name='Турнір')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Голи господарі')),
                ('away_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Голи гості')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Матч завершено')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчі',
                'ordering': ['-date'],
            },
        ),
    ]
