# Generated by Django 6.0.1 on 2026-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='matches/bg/', verbose_name='Фонове фото матчу'),
        ),
    ]
