# Generated by Django 6.0.1 on 2026-02-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Назва команди')),
                ('league', models.CharField(choices=[('SUPER', 'Суперліга'), ('FIRST', 'Перша Ліга')], default='SUPER', max_length=10, verbose_name='Дивізіон')),
                ('team_logo', models.ImageField(upload_to='table_logos/', verbose_name='Емблема')),
                ('games_played', models.PositiveIntegerField(default=0, verbose_name='І')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='В')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='Н')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='П')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('is_our_team', models.BooleanField(default=False, verbose_name='Наш клуб?')),
            ],
            options={
                'verbose_name': 'Рядок таблиці',
                'verbose_name_plural': 'Турнірна таблиця',
                'ordering': ['league', '-points', '-wins'],
            },
        ),
    ]
