# Generated by Django 6.0.1 on 2026-02-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_tournamenttable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttable',
            name='broadcast_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на трансляцію (YouTube)'),
        ),
        migrations.AddField(
            model_name='tournamenttable',
            name='weather',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Погода (напр. +15, Ясно)'),
        ),
    ]
