# Generated by Django 6.0.1 on 2026-02-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_tournamenttable_broadcast_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamenttable',
            name='broadcast_link',
        ),
        migrations.RemoveField(
            model_name='tournamenttable',
            name='weather',
        ),
        migrations.AddField(
            model_name='match',
            name='broadcast_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на трансляцію (YouTube)'),
        ),
        migrations.AddField(
            model_name='match',
            name='weather',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Погода (напр. +15, Ясно)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_logo',
            field=models.ImageField(blank=True, null=True, upload_to='matches/', verbose_name='Лого гостей'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=100, verbose_name='Гості'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_logo',
            field=models.ImageField(blank=True, null=True, upload_to='matches/', verbose_name='Лого господарів'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(default='Покрова АМП', max_length=100, verbose_name='Господарі'),
        ),
    ]
