# Generated by Django 6.0.1 on 2026-02-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_tournamenttable_broadcast_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stadium_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на Google Maps'),
        ),
    ]
