# Generated by Django 6.0.1 on 2026-02-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_stadium_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_scorers',
            field=models.TextField(blank=True, help_text='Кожне прізвище з нового рядка', null=True, verbose_name='Автори голів (Гості)'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_scorers',
            field=models.TextField(blank=True, help_text='Кожне прізвище з нового рядка', null=True, verbose_name='Автори голів (Господарі)'),
        ),
    ]
