# Generated by Django 6.0.1 on 2026-02-09 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_away_scorers_match_home_scorers'),
        ('team', '0005_alter_player_options_remove_player_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='squad',
            field=models.ManyToManyField(blank=True, related_name='matches_in_squad', to='team.player', verbose_name='Склад команди на цей матч'),
        ),
        migrations.CreateModel(
            name='MatchVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час голосу')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='matches.match', verbose_name='Матч')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_votes', to='team.player', verbose_name='Гравець')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Голос за гравця',
                'verbose_name_plural': 'Голоси',
                'unique_together': {('match', 'user')},
            },
        ),
    ]
