# Generated by Django 6.0.1 on 2026-03-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_squad_matchvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_type',
            field=models.CharField(choices=[('MAIN', 'Покрова (Основна)'), ('SECOND', 'Покрова 2')], default='MAIN', max_length=10, verbose_name='Яка команда грає'),
        ),
    ]
