# Generated by Django 6.0.1 on 2026-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_match_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_logo_width',
            field=models.PositiveIntegerField(default=80, help_text='Змініть це число (наприклад, 60, 80, 100), щоб підігнати розмір логотипу під дизайн.', verbose_name='Ширина лого гостей (px)'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_logo_width',
            field=models.PositiveIntegerField(default=80, help_text='Змініть це число (наприклад, 60, 80, 100), щоб підігнати розмір логотипу під дизайн.', verbose_name='Ширина лого господарів (px)'),
        ),
        migrations.AddField(
            model_name='tournamenttable',
            name='logo_width',
            field=models.PositiveIntegerField(default=40, help_text='Стандартно 40px для таблиці. Збільште або зменште за потреби.', verbose_name='Ширина логотипу (px)'),
        ),
    ]
