# Generated by Django 6.0.1 on 2026-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок досягнення')),
                ('year', models.CharField(help_text='Наприклад: 2024 або Осінь 2023', max_length=50, verbose_name='Рік або Сезон')),
                ('description', models.TextField(verbose_name='Опис перемоги')),
                ('image_main', models.ImageField(upload_to='achievements/', verbose_name='Головне фото (кубок/команда)')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Додаткове фото 1')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Додаткове фото 2')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Досягнення',
                'verbose_name_plural': 'Досягнення',
                'ordering': ['-date_added'],
            },
        ),
    ]
