# Generated by Django 6.0.1 on 2026-02-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва альбому')),
                ('description', models.TextField(blank=True, verbose_name="Опис (необов'язково)")),
                ('cover_image', models.ImageField(upload_to='albums/covers/', verbose_name='Обкладинка альбому')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбоми',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='albums/photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name="Підпис (необов'язково)")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.photoalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотографія',
                'verbose_name_plural': 'Фотографії',
            },
        ),
    ]
