# Generated by Django 6.0.1 on 2026-02-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('number', models.PositiveIntegerField(verbose_name='Ігровий номер')),
                ('position', models.CharField(choices=[('GK', 'Воротар'), ('DF', 'Захисник'), ('MF', 'Півзахисник'), ('FW', 'Нападник')], max_length=2, verbose_name='Позиція')),
                ('photo', models.ImageField(upload_to='players/', verbose_name='Фото гравця')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('description', models.TextField(blank=True, verbose_name='Біографія')),
            ],
            options={
                'verbose_name': 'Гравець',
                'verbose_name_plural': 'Гравці',
                'ordering': ['number'],
            },
        ),
    ]
