# Generated by Django 6.0.1 on 2026-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='description',
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0, verbose_name='Гольові передачі'),
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Біографія/Опис'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Забито голів'),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зріст (см)'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний у складі'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.PositiveIntegerField(default=0, verbose_name='Зіграно матчів'),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вага (кг)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
    ]
