# Generated by Django 6.0.1 on 2026-02-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_player_description_player_assists_player_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Учасник клубу', 'verbose_name_plural': 'Склад клубу'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='birth_year',
            field=models.IntegerField(default=2000, verbose_name='Рік народження'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='По батькові'),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('керівництво', 'Керівництво'), ('тренер', 'Тренерський штаб'), ('воротар', 'Воротар'), ('захисник', 'Захисник'), ('півзахисник', 'Півзахисник'), ('нападник', 'Нападник'), ('лікар', 'Медичний штаб'), ('масажист', 'Масажист'), ('медіа', 'Медіа-служба'), ('духівник', 'Духовний наставник')], default='нападник', max_length=30, verbose_name='Роль/Позиція'),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зріст (см)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ігровий номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='players/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вага (кг)'),
        ),
    ]
