# Generated by Django 6.0.1 on 2026-02-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_player_options_remove_player_assists_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['number'], 'verbose_name': 'Учасник клубу', 'verbose_name_plural': 'Склад клубу'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='player',
            name='role',
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0, verbose_name='Гольові передачі'),
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Біографія/Опис'),
        ),
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Забито голів'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний у складі'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.PositiveIntegerField(default=0, verbose_name='Зіграно матчів'),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Воротар'), ('DF', 'Захисник'), ('MF', 'Півзахисник'), ('FW', 'Нападник'), ('ADM', 'Керівництво'), ('COA', 'Тренер'), ('DOC', 'Медичний штаб'), ('MAS', 'Масажист'), ('MED', 'Медіа-служба'), ('SPR', 'Духовний наставник')], default='FW', max_length=3, verbose_name='Позиція/Роль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зріст (см)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ігровий номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(upload_to='players/', verbose_name='Фото гравця'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вага (кг)'),
        ),
    ]
