# Generated by Django 6.0.1 on 2026-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_player_options_remove_player_birth_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-is_active', 'position', 'number'], 'verbose_name': 'Гравець', 'verbose_name_plural': 'Команда'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='player',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0, verbose_name='Асисти'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Голи'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зріст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='matches_played',
            field=models.PositiveIntegerField(default=0, verbose_name='Матчі'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, upload_to='players/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Воротар'), ('DF', 'Захисник'), ('MF', 'Півзахисник'), ('FW', 'Нападник'), ('ADM', 'Керівництво'), ('COA', 'Тренер'), ('DOC', 'Медичний штаб'), ('MAS', 'Масажист'), ('MED', 'Медіа-служба'), ('SPR', 'Духовний наставник')], max_length=3, verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вага'),
        ),
    ]
