# Generated by Django 6.0.1 on 2026-03-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_player_options_remove_player_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team', 'position', 'number'], 'verbose_name': 'Учасник', 'verbose_name_plural': 'Команда'},
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('TEAM_1', 'Покрова'), ('TEAM_2', 'Покрова 2'), ('CLUB', 'Загальноклубний штаб')], default='TEAM_1', max_length=10, verbose_name='Команда'),
        ),
    ]
