# Generated by Django 6.0.1 on 2026-03-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_player_options_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Біографія'),
        ),
    ]
