# Generated by Django 6.0.1 on 2026-03-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_player_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='height',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weight',
        ),
        migrations.AddField(
            model_name='player',
            name='full_size_photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/full_size/', verbose_name='Фото в повний зріст (Детально)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, upload_to='players/', verbose_name='Фото (Портрет для карток)'),
        ),
    ]
