# Generated by Django 6.0.1 on 2026-02-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FanPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок фото')),
                ('image', models.ImageField(upload_to='fan_zone/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фото фан-зони',
                'verbose_name_plural': 'Фото фан-зони',
            },
        ),
    ]
