# Generated by Django 6.0.1 on 2026-02-04 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('delivery_method', models.CharField(choices=[('NP', 'Нова Пошта'), ('PICKUP', 'Самовивіз (Львів)')], default='NP', max_length=10, verbose_name='Доставка')),
                ('delivery_address', models.CharField(blank=True, max_length=200, verbose_name='Адреса / Відділення')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('status', models.CharField(choices=[('NEW', 'Нове'), ('CONFIRMED', 'Підтверджено'), ('SENT', 'Відправлено'), ('CANCELED', 'Скасовано')], default='NEW', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('category', models.CharField(choices=[('TSHIRT', 'Футболки'), ('HOODIE', 'Худі'), ('SCARF', 'Шарфи'), ('SOUVENIR', 'Сувеніри'), ('OTHER', 'Інше')], default='OTHER', max_length=20, verbose_name='Категорія')),
                ('price', models.IntegerField(verbose_name='Ціна (грн)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='shop/', verbose_name='Фото товару')),
                ('is_available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Ціна на момент покупки')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
