# Generated by Django 6.0.1 on 2026-02-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата карткою (Visa/Mastercard)'), ('cod', 'Оплата при отриманні')], default='cod', max_length=10),
        ),
    ]
